---
# 服务配置
server:
  # 服务端口
  port: 12015

# Spring 配置
spring:
  application:
    # 应用名称
    name: ${project.artifactId}

# 日志配置
logging:
  level:
    # 默认日志级别
    root: INFO
    # 项目包日志级别
    io.github.atengk: DEBUG
---
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
---
# 邮箱配置
spring:
  mail:
    # SMTP 服务地址
    host: smtp.qq.com
    # SMTP 服务端口，常见值：25、465、587
    port: 587
    # 发件账号
    username: 2385569970@qq.com
    # 发件密码或授权码，生产环境建议使用环境变量注入
    password: ${MAIL_PASSWORD:change-me}
    # 默认编码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          # 开启 SMTP 认证
          auth: true
          # 启用 STARTTLS
          starttls:
            enable: true
          # 连接超时时间，单位毫秒
          connectiontimeout: 10000
          # 读超时时间，单位毫秒
          timeout: 10000
          # 写超时时间，单位毫秒
          writetimeout: 10000
