server:
  port: 19001
spring:
  application:
    name: ${project.artifactId}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: true # 开启 multipart 懒加载
logging:
  level:
    root: info
    io.github.atengk: debug
---
# Spring AI 配置
spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:0.5b
          temperature: 0.7
          max-tokens: 2048
          top-p: 1.0
      embedding:
        options:
          model: qwen3-embedding:0.6b