server:
  port: 19001
spring:
  application:
    name: ${project.artifactId}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: true # 开启 multipart 懒加载
logging:
  level:
    root: info
    io.github.atengk: debug
---
# Spring AI 配置
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.chatanywhere.tech
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
          max-tokens: 2048
          top-p: 1.0
      embedding:
        options:
          model: text-embedding-3-small